# Generated by Django 5.2.7 on 2025-10-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_userprofile_favoriteplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteplayer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='katalog_pro_name_994cd9_idx',
            old_name='katalog_pro_name_3f0b3e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='katalog_pro_categor_92d47d_idx',
            old_name='katalog_pro_categor_5e3d8a_idx',
        ),
        migrations.DeleteModel(
            name='FavoritePlayer',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
