# Generated by Django 5.2.7 on 2025-10-21 17:17

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('bio', models.TextField(blank=True)),
                ('category', models.CharField(choices=[("women's single", "Women's Single"), ("men's single", "Men's Single"), ("women's double", "Women's Double"), ("men's double", "Men's Double"), ('mixed double', 'Mixed Double')], default="women's single", max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('injured', 'Injured'), ('retired', 'Retired')], default='active', max_length=10)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('world_rank', models.PositiveIntegerField(blank=True, help_text='Peringkat dunia saat ini', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(blank=True, help_text='Pilih pemain lain sebagai partner (jika pemain ganda)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.player')),
            ],
        ),
    ]
