# Generated by Django 5.2.7 on 2025-10-24 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
