# Generated by Django 5.2.7 on 2025-10-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_player_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='favorited_by',
        ),
    ]
