# Generated by Django 5.2.7 on 2025-10-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_player_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
