# Generated by Django 5.2.7 on 2025-10-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smash_talk', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
